Repository ashishb/adb-enhanced, pull requests merged in 2024-04, with the labels that each got.

#237 ci: increase timeout for a few tests
  .github/workflows/adbe-installtests.yml
  .github/workflows/adbe-unittests.yml
Labels: enhancement, size:XS

#240 chore: add status badge for API 34 CI build
  README.md
Labels: enhancement, size:XS

#239 ci: switch from `macos-latest` -> `ubuntu-latest` + KVM
  .github/workflows/adbe-unittests-api16.yml
  .github/workflows/adbe-unittests-api21.yml
  .github/workflows/adbe-unittests-api22.yml
  .github/workflows/adbe-unittests-api23.yml
  .github/workflows/adbe-unittests-api24.yml
  .github/workflows/adbe-unittests-api25.yml
  .github/workflows/adbe-unittests-api26.yml
  .github/workflows/adbe-unittests-api27.yml
  .github/workflows/adbe-unittests-api28.yml
  .github/workflows/adbe-unittests-api29.yml
  .github/workflows/adbe-unittests-api30.yml
  .github/workflows/adbe-unittests-api31.yml
  .github/workflows/adbe-unittests-api32.yml
  .github/workflows/adbe-unittests-api33.yml
  .github/workflows/adbe-unittests-api34.yml
  .github/workflows/adbe-unittests.yml
  .github/workflows/install-adb-enhanced-from-homebrew.yml
Labels: enhancement, size:L

#242 ci: add KVM on a missing test
  .github/workflows/adbe-unittests.yml
Labels: enhancement, size:S

#241 ci: enable AVD caching and KVM in adbe-installtests.yml
  .github/workflows/adbe-installtests.yml
Labels: enhancement, size:M

#234 Implement setting and clearing debug app
  adbe/adb_enhanced.py
  adbe/main.py
  tests/adbe_tests.py
Labels: enhancement, size:S, lgtm

#243 ci: disable emulator metrics explicitly
  .github/workflows/adbe-unittests-api16.yml
  .github/workflows/adbe-unittests-api21.yml
  .github/workflows/adbe-unittests-api22.yml
  .github/workflows/adbe-unittests-api23.yml
  .github/workflows/adbe-unittests-api24.yml
  .github/workflows/adbe-unittests-api25.yml
  .github/workflows/adbe-unittests-api28.yml
  .github/workflows/adbe-unittests-api29.yml
  .github/workflows/adbe-unittests-api30.yml
  .github/workflows/adbe-unittests-api31.yml
Labels: enhancement, size:M
